### PR TITLE
Add initial Dockerfile

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@gadinaor please review

**Comment by gadinaor** [comment]
@gliptak can you please share some context on the purpose or use case for this Docker file  ?

**Comment by gliptak** [comment]
@gadinaor many tools (command-line) tools choose to have a Dockerfile or publish to Dockerhub allowing users to run the tool without local build environment setup. Below is example run:

```
➜ docker build --tag rbac-tool:latest .
Sending build context to Docker daemon  718.3kB
Step 1/11 : FROM golang:1.15-alpine as builder
 ---> 1de1afaeaa9a
Step 2/11 : RUN apk --no-cache add git make gcc musl-dev zip
 ---> Using cache
 ---> e562a0617e0b
Step 3/11 : WORKDIR /go/src/github.com/alcideio/rbac-tool/
 ---> Using cache
 ---> 2a1cfdcce020
Step 4/11 : ADD . /go/src/github.com/alcideio/rbac-tool
 ---> Using cache
 ---> 2873fb2e9bec
Step 5/11 : RUN make build
 ---> Using cache
 ---> de38e8ad3e24
Step 6/11 : FROM alpine:3.12 as prod
 ---> d6e46aa2470d
Step 7/11 : LABEL maintainer=alcideio
 ---> Using cache
 ---> 03164607d958
Step 8/11 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> 65a2f1a1edd7
Step 9/11 : COPY --from=builder /go/src/github.com/alcideio/rbac-tool/bin/rbac-tool /usr/local/bin
 ---> Using cache
 ---> e28f63a6db1d
Step 10/11 : ENTRYPOINT ["rbac-tool"]
 ---> Using cache
 ---> 31b620945d31
Step 11/11 : CMD ["help"]
 ---> Using cache
 ---> 651062f34c6c
Successfully built 651062f34c6c
Successfully tagged rbac-tool:latest
➜ docker run --rm rbac-tool:latest
rbac-tool

Usage:
  rbac-tool [command]

Available Commands:
  auditgen        Generate RBAC policy from Kubernetes audit events
  bash-completion Generate bash completion. source < (advisor bash-completion)
  generate        Generate Role or ClusterRole and reduce the use of wildcards
  help            Help about any command
  lookup          RBAC Lookup by subject (user/group/serviceaccount) name
  policy-rules    RBAC List Policy Rules For subject (user/group/serviceaccount) name
  version         Print rbac-tool version
  visualize       A RBAC visualizer

Flags:
  -h, --help      help for rbac-tool
  -v, --v Level   number for the log level verbosity

Use "rbac-tool [command] --help" for more information about a command.
```

**Comment by gadinaor** [comment]
@gliptak thanks !
This repo leverage goreleaser as the binary build and release.
It does have the ability to release docker images - so it would be best for us to make this enhancement using goreleaser.

**Comment by gliptak** [comment]
@gadinaor as per the goreleaser documentation the first step is to create a Dockerfile

https://goreleaser.com/customization/docker/#how-it-works

**Comment by gadinaor** [comment]
That's correct - however the docker file doesn't need to take care of the rbac-tool binary build.

See example here: https://github.com/alcideio/iskan

**Pull request closed without merging**
